{100}{}{Calm rebel faction.}
{101}{}{Destroy the Mutant leader.}
{102}{}{Destroy the source of the Mutants.}
{103}{}{Find the Water Chip.}
{104}{}{Find the Water Thief.}
{105}{}{Cure Jarvis of Radscorpion Poison.}
{106}{}{Make Poison Antidote.}
{107}{}{Rescue Tandi from the Raiders.}
{108}{}{Stop the Radscorpions.}
{109}{}{Help Saul.}
{110}{}{Kill Killian.}
{111}{}{Rescue Sinthia.}
{112}{}{Save Trish.}
{113}{}{Stop Gizmo.}
{114}{}{Bust the Skulz gang.}
{115}{}{Destroy the Super Mutants at the Watershed.}
{116}{}{Fix the Necropolis water pump.}
{117}{}{Destroy Deathclaw.}
{118}{}{Dispose of Jain.}
{119}{}{Dispose of merchant.}
{120}{}{Find the missing caravans.}
{121}{}{Steal necklace from the Merchants.}
{122}{}{Become an Initiate.}
{123}{}{Rescue Initiate from the Hub.}
{124}{}{Disarm Traps for the Facility.}
{125}{}{Turn on power for the Glow.}
{126}{}{Become a Blade.}
{127}{}{Deliver Locket for Romero.}
{128}{}{Deliver package from the Gun Runners.}
{129}{}{Find Children spy in the Followers.}
{130}{}{Fix hydroponic farms in Adytum.}
{131}{}{Rescue Jason Zimmerman.}
{132}{}{Stop the Gangs from attacking Adytum.}
