# CUSTOM Korean localization
{0}{}{연사}
{1}{}{도주}
{2}{}{무기 선호}
{3}{}{거리}
{4}{}{공격 대상}
{5}{}{약물 사용}

{10}{}{완료}
{11}{}{취소}

{99}{}{해당 없음}
{100}{}{항상!}
{101}{}{가끔. 나를 맞혀도 신경 쓰지 마.}
{102}{}{나를 맞히지 않을 때만}
{103}{}{나를 맞히지 않도록 조심해서}
{104}{}{절대로 나를 맞히지 않을 때만}

{200}{}{겁이 많으면 도망쳐}
{201}{}{손가락만 다쳐도 도망쳐}
{202}{}{조금만 피가 나도 도망쳐}
{203}{}{상태가 좋지 않으면 도망쳐}
{204}{}{심하게 다치면 도망쳐}
{205}{}{절대 도망치지 마}
{300}{}{상관없음}
{301}{}{근접 무기}
{302}{}{근접 무기 우선, 그다음 원거리}
{303}{}{원거리 무기 우선, 그다음 근접}
{304}{}{원거리 무기}
{305}{}{맨손}

{400}{}{내 곁에 있어}
{401}{}{돌격!}
{402}{}{멀리서 저격해}
{403}{}{알아서 움직여}
{404}{}{현재 위치를 지켜}

{500}{}{나를 공격하는 적}
{501}{}{가장 강한 적}
{502}{}{가장 약한 적}
{503}{}{원하는 적}
{504}{}{가장 가까운 적}

{600}{}{약물은 쓰지 마}
{601}{}{조금 다치면 스팀팩 사용}
{602}{}{많이 다치면 스팀팩 사용}
{603}{}{가끔 아무 약물이나 사용}
{604}{}{언제든 아무 약물이나 사용}
