# OPTIONS Korean localization
{0}{}{저장}
{1}{}{불러오기}
{2}{}{환경설정}
{3}{}{게임 종료}
{4}{}{완료}

{100}{}{게임 환경설정}
{101}{}{게임 난이도}
{102}{}{전투 난이도}
{103}{}{폭력 표현}
{104}{}{대상 강조}
{105}{}{전투 연출}
{106}{}{전투 메시지}
{107}{}{전투 도발}
{108}{}{언어 필터}
{109}{}{달리기}
{110}{}{자막}
{111}{}{아이템 강조}
{112}{}{전투 속도}
{113}{}{텍스트 표시 시간}
{114}{}{전체 음량}
{115}{}{음악/영상 음량}
{116}{}{효과음 음량}
{117}{}{음성 음량}
{118}{}{밝기}
{119}{}{마우스 감도}
{120}{}{기본값}
{121}{}{취소}
{122}{}{플레이어 속도에도 적용}
{123}{}{핍보이 음성}

{201}{}{켬}
{202}{}{끔}
{203}{}{쉬움}
{204}{}{보통}
{205}{}{어려움}
{206}{}{약함}
{207}{}{보통}
{208}{}{거침}
{209}{}{보통}
{210}{}{가장 빠름}
{211}{}{자세히}
{212}{}{간단히}
{213}{}{조준할 때만}
{214}{}{없음}
{215}{}{최소}
{216}{}{최대 유혈}
{217}{}{느림}
{218}{}{빠름}
{219}{}{항상}
{220}{}{많음}
{221}{}{조용히}
{222}{}{크게}
{223}{}{밝게}
{224}{}{넓게}
{300}{}{완료}
{301}{}{일시 정지}

{1000}{}{죄송합니다. 데모 버전에서는}
{1001}{}{환경설정 메뉴를 사용할 수 없습니다.}
